### ISSUE TITLE
ARGS warning message is misleading

### ISSUE THREAD

**Issue by mathias-lang-sociomantic** [sociomantic-tsunami/makd#103]
Whenever ARGS is empty, we get the following message:
```
Warning: Your ARGS list looks weird, maybe you mistakenly used ARGS=list("string")? If so, please use ARGS=["string"] instead.
```

The message suggest to use `ARGS=...` but since MakD v2.0.0 it's a builtin variable which should never be updated in place, yet this message recommends it.

**Comment by leandro-lucarella-sociomantic** [comment]
How was this warning triggered by the way? Now that it is a built-in it seems weird that that happens...

**Comment by leandro-lucarella-sociomantic** [comment]
Oh, with empty args. To use empty args I think we need to change the `-s` to `empty` or something, which it's sort of a new feature. I guess for now I will add an error if `ARGS` is empty. What happens after the warning is triggered, does it fail to build the package?

**Comment by mathias-lang-sociomantic** [comment]
I was upgrading from v1.x.x and forgot to change `ARGS=[...]` to `ARGS.update` IIRC.

**Comment by leandro-lucarella-sociomantic** [comment]
OK, in this case you should get a warning, and I will suggest that case. If we want to support virtual packages in the future we might make use `ARGS.append(None)` or something to make it more explicit.

**Comment by leandro-lucarella-sociomantic** [comment]
Done in the PR.
