### ISSUE TITLE
Makd v1.11.0 / v2.1.0 are broken

### ISSUE THREAD

**Issue by mathias-lang-sociomantic** [sociomantic-tsunami/makd#111]
Running MakD v2.1.0 will yield `sed: -e expression #6, char 29: unknown option to `s'`.
Moreover, `Version.d`'s module name is not replaced, leading to the following code:
```
module @MODULE@;
```

Which obviously fails to compile.

**Comment by leandro-lucarella-sociomantic** [comment]
This potentially affects v1.10.x and v2.0.x too (if some funny chars come in them).

**Comment by mathias-lang-sociomantic** [comment]
Tested on my side, v2.1.1 works fine

**Comment by leandro-lucarella-sociomantic** [comment]
Releasing! Sorry for the trouble!
