### ISSUE TITLE
Debian package versioning broken with pre-releases

### ISSUE THREAD

**Issue by leandro-lucarella-sociomantic** [sociomantic-tsunami/makd#117]
# Part 1

Makd translate project's version to debian package compatible versions and as part of this process, a *debian_revision* is added with the distribution name, gor example:
`v1.2.1 -> 1.2.1-xenial`

The problem with this scheme is it was done before we actually started using pre-releases, which include a hyphen (`-`) too. So if we add a pre-release part to that example, we end up with:
`v1.2.1-rc.1 -> 1.2.1-rc.1-xenial`

Hyphens are special in [Debian version](https://www.debian.org/doc/debian-policy/#version). **Very** special. If only one is given, then everything after the hyphen is considered a *debian_revision*, but if more than one is given, then all of it is considered part of the *upstream_version*.

So the version string will be parsed differently by Debian for both examples:

1. `1.2.1-xenial`

   * *upstream_version*: `1.2.1`
   * *debian_revision*: `xenial`

2. `1.2.1-rc.1-xenial`

   * *upstream_version*: `1.2.1-rc.1-xenial`
   * *debian_revision*: (empty)

Because of this and how Debian parse versions (splitting in steps all non-numeric chars and comparing those lexicographically and comparing the numeric parts numerically), we end up with a *rc* version that is considered newer than a final version:

```console
$ if dpkg --compare-versions 1.2.1-xenial gt 1.2.1-rc.1-xenial; then echo YAY; else echo DAMN; fi
DAMN
```

Debian uses tilde (`~`) in a way that is similar to pre-releases or build metadata in semver. Basically `1.2.1~whatever` will be always older than `1.2.1`, and `1.2.1~~whatever` will be always even older than `1.2.1~~whatever`. According to Debian docs:

> The lexical comparison is a comparison of ASCII values modified so that all the letters sort earlier than all the non-letters and so that a tilde sorts before anything, even the end of a part. For example, the following parts are in sorted order from earliest to latest: `~~`, `~~a`, `~`, the empty part, `a`.

So the obvious fix is to just replace the hyphen with tilde (we are already using tilde widely):

```console
$ if dpkg --compare-versions 1.2.1-xenial gt 1.2.1~rc.1-xenial; then echo YAY; else echo DAMN; fi
YAY
```

This is easy except that there is also the versions produced from untagged versions.

# Part 2

Untagged versions (versions produced from a non-tagged commit or from a dirty repo) produce a version string that is a bit more complicated because it adds how many commits are we ahead from last tag. This is also already translated by Makd to a debian package compatible versions like this example:
`v1.2.1-rc.1-4-gea7105b-dirty -> 1.2.1~rc.1+4~dirty.20160202160552~ea7105b-xenial`

In principle this looks good, but in reality a dirty package should be newer than the same non-dirty version (as is the tagged version with some changes) so even when is in reality not related to this, we should fix that, just changing the tilde for a plus before the `dirty` should do it:
```console
$ if dpkg --compare-versions 1.2.1~rc.1+4~dirty.20160202160552~ea7105b-xenial gt 1.2.1~rc.1+4~ea7105b-xenial; then echo YAY; else echo DAMN; fi
DAMN
$ if dpkg --compare-versions 1.2.1~rc.1+4+dirty.20160202160552~ea7105b-xenial gt 1.2.1~rc.1+4~ea7105b-xenial; then echo YAY; else echo DAMN; fi
YAY
```

By adjusting just this bit, all seems to work as it should with Debian versions. Here is a simple test bed to verify this:

```sh
compare_all()
{
    while true
    do
        v=$1; shift
        test -n "$1" || 
            break
        for op in eq gt lt
        do
            dpkg --compare-versions "$v" $op "$1" && printf "%40s  %s  %s\n" "$v" $op "$1"
        done
    done
}
$ compare_all \
    1.8.3 1.8.3~rc.2+dirty.20180105195104 \
    1.8.3~rc.2 \
    1.8.3~rc.1+1+dirty.20180105195104~67cf \
    1.8.3~rc.1+1~67cf \
    1.8.3~rc.1 \
    1.8.2+4+dirty.20180105195323~abcf \
    1.8.2+4+dirty.20180105195104~abcf \
    1.8.2+4~abcf \
    1.8.2+2~123f \
    1.8.2 \
    1.8.2~rc.1+1~1234 \
    1.8.2~rc.1 \
    1.8.2~alpha.2+3~1234 \
    1.8.2~alpha.2 \
    1.8.2~alpha.1+1~1235 \
    1.8.2~alpha.1 \
    1.8.0+10~abfe \
    1.8.0
```

Results are:
```
                                   1.8.3  gt  1.8.3~rc.2+dirty.20180105195104
         1.8.3~rc.2+dirty.20180105195104  gt  1.8.3~rc.2
                              1.8.3~rc.2  gt  1.8.3~rc.1+1+dirty.20180105195104~67cf
  1.8.3~rc.1+1+dirty.20180105195104~67cf  gt  1.8.3~rc.1+1~67cf
                       1.8.3~rc.1+1~67cf  gt  1.8.3~rc.1
                              1.8.3~rc.1  gt  1.8.2+4+dirty.20180105195323~abcf
       1.8.2+4+dirty.20180105195323~abcf  gt  1.8.2+4+dirty.20180105195104~abcf
       1.8.2+4+dirty.20180105195104~abcf  gt  1.8.2+4~abcf
                            1.8.2+4~abcf  gt  1.8.2+2~123f
                            1.8.2+2~123f  gt  1.8.2
                                   1.8.2  gt  1.8.2~rc.1+1~1234
                       1.8.2~rc.1+1~1234  gt  1.8.2~rc.1
                              1.8.2~rc.1  gt  1.8.2~alpha.2+3~1234
                    1.8.2~alpha.2+3~1234  gt  1.8.2~alpha.2
                           1.8.2~alpha.2  gt  1.8.2~alpha.1+1~1235
                    1.8.2~alpha.1+1~1235  gt  1.8.2~alpha.1
                           1.8.2~alpha.1  gt  1.8.0+10~abfe
                           1.8.0+10~abfe  gt  1.8.0
```

Changing the scheme to this might prove tricky though, unless we keep assuming a lot about what an *upstream_version* could be (which we probably should anyway, otherwise versions won't work), but it seems to fix the issue.

# Pending Issues

When talking about non tagged versions, there is also the problem with semver. Unfortunately I don't think there is a way to map this behaviour to semver because I couldn't find any way to express v1.8.2+3 commits for example. Semver requires all X Y and Z in vX.Y.Z to be numbers. If we were to use `-` as a separator, then v1.8.3-3 would be older than v1.8.3 which is not what we want. If we use metadata separator, it doesn't have an effect on version ordering.

I guess this is not a big issue, as semver is not really for deployment but for dependency declaration and being so it should only refer to released tags. But is something to have in mind. Dirty information could be added as build metadata but it isn't exactly what we want either.

I guess we should just live with versions like `v1.2.1-rc.1-4-gea7105b-dirty` not being really semver compatible.

/cc @mihails-strasuns-sociomantic @nemanja-boric-sociomantic  @gavin-norman-sociomantic

**Comment by mihails-strasuns-sociomantic** [comment]
> In principle this looks good, but in reality a dirty package should be newer than the same non-dirty version

Is it really needed? I mean I can't imagine a case when I would want to upgrade to the dirty version automatically.

**Comment by leandro-lucarella-sociomantic** [comment]
> Is it really needed?

No, but IMHO it's what it makes sense if we want to follow the "principle of least astonishment". A dirty package of a particular version will always be more *recent* than the original version.

I know it will only matter for development and then only if you are automatically updating using an apt repo, but still if it can be done in a way that it's more intuitive for users I don't see why we shouldn't.
