### ISSUE TITLE
Should `test/***/main.d` targets be run inside `$MAKD_TMPDIR` directory

### ISSUE THREAD

**Issue by nemanja-boric-sociomantic** [sociomantic-tsunami/makd#35]
Currently, on `make test`, tests are run inside whatever the current directory is (most likely `$C`). If the tests are creating artifacts then they are mixed with the working directory contents.

Should it be better if the Makd automatically runs these tests inside `$MAKD_TMPDIR`, and even if it would create a sandbox for each `test-*` target?

**Comment by mihails-strasuns-sociomantic** [comment]
This is generalization of turtle approach which has already worked very good - I naturally support it.

**Comment by leandro-lucarella-sociomantic** [comment]
> Should it be better if the Makd automatically runs these tests inside $MAKD_TMPDIR, and even if it would create a sandbox for each test-* target?

I wonder if some dockerness should be involved too. But maybe for now we can just (re-)create a per-test directory in the test and use that as the current working directory when running them.

That said, if you don't make sure to use proper temporary space in the test itself, if for some reason you want to run it manually, you will bump into the same problem, so I wonder if ocean should get an utility function to create a temporary directory that is discarded after the test ends instead.

Something like:
```d
int main()
{
    import ocean.core.Test;
    auto sandbox = init_sandbox();
    scope (success) clean_sandbox(sandbox);

    // ...
}
```

Is also hard to know in advance if it makes sense to remove the sandbox... always? when it succeed (as one probably won't want to inspect the results)? Never? Having options to control this could make sense (as well as option to select where to create the sandbox). Maybe env vars can be used for this.

**Comment by leandro-lucarella-sociomantic** [comment]
I think we should definitely go for the explicit sandbox, as there is also the problem of tests that might have other file resources they could need to read to perform the test. In this case using a different CWD won't work. I think the test needs to know where are they being executed.

**Comment by leandro-lucarella-sociomantic** [comment]
I'm tempted to close as `wontfix`.

**Comment by nemanja-boric-sociomantic** [comment]
Feel free to do that. The next ocean release will have `Sandbox` facility, so this is not a problem anymore.
