### ISSUE TITLE
Create a logo for Makd

### ISSUE THREAD

**Issue by leandro-lucarella-sociomantic** [sociomantic-tsunami/makd#4]
## Summary

Create a logo for a D build system we just open-sourced called Makd
## Brief Description

This is a build system to build D software base on GNU Make, another open source project. It basically transforms D source code to a program that can be ran.
## Why Makd is cool / important?

Makd simplifies the life of the developer by taking care or a lot of bookkeeping and details about how a project is built, like tracking dependencies between files and deciding when something actually needs to be rebuilt. It also adds some beauty to the original GNU Make, by providing a more concise and colourful output.
## Ideas for the Logo

Since is a build system, the most obvious choice seems to be something build related, maybe some cranes moving some blocks, or also there could be some graph involved, as it track dependencies. Since it's mainly targeted to D projects, maybe some D could be involved, and maybe some red too, as is the identifying colour for D (although this probably conflicts with Sociomantic colours, so I'll leave that to you).

Here is, as an example, a similar project that has a logo: http://scons.org/ (although I don't find that logo particularly beautiful :P)
## Final Output

To be used on GitHub repo, stickers, etc. potentially even external website (if one is made).
## Extra Goodies

Colour scheme and suggested font for further work on a potential website.

**Comment by dylan-cromwell-sociomantic** [comment]
@leandro-lucarella-sociomantic this has been submitted to Design. I will follow the project to its completion and post iterations here for your (and others') feedback. I have altered the deadline to 1.5 months later, 30/9/16 as I think giving more time is reasonable.

Also is it written "makd" or "Makd" ?

**Comment by leandro-lucarella-sociomantic** [comment]
> Also is it written "makd" or "Makd" ?

I would say "Makd", although I think it would be fine to use all lowercase if for some reason is better for the logo.

**Comment by dilkROM** [comment]
Hey @leandro-lucarella-sociomantic long time coming but the fantastic Khuyen has finished an early design. There are two choices / directions so far. Please let me know what you think and perhaps we can meet and discuss a bit in-person.

[makd.pdf](https://github.com/sociomantic-tsunami/makd/files/539180/makd.pdf)

**Comment by leandro-lucarella-sociomantic** [comment]
Hi @dilkROM, thanks for the update! I think the second option is more on track, the first one seems too "nice" for a project like this one, too visual (even when it has a wink to the low level nature of the project by using binary). I think the second option is still too round-ish, and it feels too "web" too IMHO. When I see the logo I think it's a JS project.

For this project I think it would represent it better a monospaced and more common "console" font, like [Terminus](http://terminus-font.sourceforge.net/) ([screenshots](http://terminus-font.sourceforge.net/shots.html)) or "[DejaVu](http://dejavu-fonts.org/wiki/Main_Page) Sans Mono". A more console-like look in general could be more suitable too, like white (or the vintage phosphor green) on black.

Also, looking at the capitalization, I think it might be better to make the project `MakD`, as make files are usually named `Makefile` with capitalized `M` (historical reasons, to make the file appear first in the directory listings, which used to be sorted in a case sensitive way), and the language D is also written with a capital D.

Finally, it would be nice to have some representation to the **building** aspect of the project (if possible), like I posted in similar projects like [Scons](http://scons.org/), building blocks, a crane or similar stuff might be suitable, but I know this might be trickier.

Thanks again! :heart:

**Comment by dylan-cromwell-sociomantic** [comment]
Hey @leandro-lucarella-sociomantic, here I am, user-jumping again. 😆 

But anyhow; the update is that I let Design know about your feedback. Stay tuned for more.

**Comment by dylan-cromwell-sociomantic** [comment]
Coming in for an update. Same as Ocean, unfortunately, the current news is as follows:

@leandro-lucarella-sociomantic as can be expected Design is very busy with their daily work and we are not at a redesign yet. I've set a meeting to catch-up and see if we can help expedite the process at all. They've requested it be July or August. I will keep you updated with any significant news but as I've been doing I will not just post comments if there is nothing important to report.

**Comment by leandro-lucarella-sociomantic** [comment]
OK, no worries. This is just a nice treat for the project that can wait!

I will remove the old deadline to avoid confusion. I will keep it without one, it will happen when it happens :)

**Comment by leandro-lucarella-sociomantic** [comment]
I don't think this will ever happen.
