### ISSUE TITLE
Remove `-unittest` from default `test/` targets flags and run unittests in `test/` via `make unittest` instead

### ISSUE THREAD

**Issue by mihails-strasuns-sociomantic** [sociomantic-tsunami/makd#41]
Current proposed solution
=====================

* Remove `-unittest` when compiling integrations tests (`test/`) because they complicate debugging.

* When getting the files to run `unittest`s for the `make unittest` target, also consider the integration tests files (in `test/`), so integrations test there still ran at least in some context.

This is a good trade-off to have integration tests still running but keeping clean runs for integration tests (also avoid a lot of duplication when running `unittest` blocks, which now  will be ran only once via the `make unittest` target).

Original issue description
====================

Originally I have pushed for keeping the flag so that internal sanity of test suite can also be validated. However practice has proven that this is almost never used. At the same time, running all unittests of all modules has also proven to complicate debugging a lot.

I propose to publicly shame me and remove that flag by default.

**Comment by leandro-lucarella-sociomantic** [comment]
As long as you are shamed in public, I'm fine with it :trollface: 

Now being serious, I'm a bit concerned about user expectations here now. People might have started putting `unittest` blocks in `test/` and they'll expect for them to be tested too. So I think we need to go at least through a deprecation phase if we are going with this.

We could do:

1. Deprecation phase (v1.8.x)

   * Add a config option to enable the new behaviour (for example `TEST_WITHOUT_UNITTEST := 1`)
   * Add a warning when this new behaviour is not enabled explaining that the default will change in the future

2. Removal phase (v2.0.0)

   * Change default behaviour to `TEST_WITHOUT_UNITTEST := 1`
   * Optionally ignore the variable and warn the user if the variable is defined saying it's not used anymore (but maybe is good to leave this option, maybe for some cases enabling unittest blocks for integrations tests is desirable).

**Comment by mathias-lang-sociomantic** [comment]
> People might have started putting unittest blocks in test/ and they'll expect for them to be tested too. So I think we need to go at least through a deprecation phase if we are going with this.

Note that for us, we can test this with:

> user:youknowho unittest path:test

It's also possible that a testsuite have unittests. What do we do in that case ?

**Comment by leandro-lucarella-sociomantic** [comment]
> user:youknowho unittest path:test

I don't understand what this means.

> It's also possible that a testsuite have unittests. What do we do in that case ?

Yeah, that too, but being a test, you never want to compile a version of it that doesn't run unittests, so instead of using `unittest` blocks to test whatever, you can just put the code in a regular function and call all your "unit test" functions at the start of the main manually.

Documentation has to be very clear about this though.

**Comment by leandro-lucarella-sociomantic** [comment]
OTOH, unittests for `test/` could be included in `make unittest`, so they won't be ran by `make integrationtest`. I think that could be a reasonable tradeoff.

**Comment by mihails-strasuns-sociomantic** [comment]
> OTOH, unittests for test/ could be included in make unittest, so they won't be ran by make integrationtest. I think that could be a reasonable tradeoff.

I think this makes perfect sense and is best of both worlds.

**Comment by leandro-lucarella-sociomantic** [comment]
Also done.
