### ISSUE TITLE
Bug in README deb config example

### ISSUE THREAD

**Issue by andreas-bok-sociomantic** [sociomantic-tsunami/makd#5]
Using the [example](https://github.com/sociomantic-tsunami/makd#example) from README generates a warning when running packaging script.

>  `list('some string')`
>  ['s', 'o', 'm', 'e', ' ', 's', 't', 'r', 'i', 'n', 'g']
> 
> `list('some', 'string')` gives 
> `list() takes at most 1 argument (2 given)`

ARGS should be defined as a literal array 

``` py
ARGS = [ 
  bin_path + '=/usr/sbin/' + bin_name + VAR.suffix,
  'README.rst=/usr/share/doc/' + pkg_name '/',
]
```

**Comment by llucax** [comment]
Fixed by d3275a0ecf650c5d1ec481af292b23426a237118.
