### ISSUE TITLE
Introduce standard `example` folder

### ISSUE THREAD

**Issue by mihails-strasuns-sociomantic** [sociomantic-tsunami/makd#59]
Having detailed well-documented usage examples improves learning curve a lot so it is common for more mature projects to provide those. Within current makd layout we are supposed to put them to `test` folder but that is not very convenient - examples may be expected to fail for the very purpose of example or imply some environment setup that is not practical for testing purpose. It is also harder to find them when they are stored in same folder as tests.

Proposal is to define new `example` top-level folder in project directory and make makd compile its content in a way similar to `test` but without actually running resulting binaries (at least by default). Bonus points for modifying `make doc` target so that those example are available in dedicated documentation section.

**Comment by leandro-lucarella-sociomantic** [comment]
It seems like a good idea. I think ideally examples should be ran too, and if it's supposed to fail check that it does fail. Maybe some sort of special metadata should be included, like which output is expected, or which exit code (including options to ignore those). So this really serves as both complete tests and documentation. But the distinction seems important enough (writing examples and tests have completely different goals even if they have a lot in common). Extending testing to be able to check for programs that are supposed to fail could be a good addition anyway.
