### ISSUE TITLE
D2: Handle packages when building allunittests

### ISSUE THREAD

**Issue by mathias-lang-sociomantic** [sociomantic-tsunami/makd#73]
When calling `make test`, MakD will generate a file `build/$F/tmp/allunittests.d` importing all files in a project and all dependencies.

In D2, if a file is called `package`, it can act as a way to import the package.
E.g. the file `src/altered/package.d` can have `module altered;` as ModuleDeclaration.

However, since MakD seems to rely on the file <-> ModuleDeclaration association, this use case will generate:

```
module allunittests;
 import ocean.core.UnitTestRunner;

 import altered.package;
```

Which will result in a compilation failure:
```
altereD/build/devel/tmp/allunittests.d(5): Error: identifier expected following package
altereD/build/devel/tmp/allunittests.d(5): Error: ';' expected
```

**Comment by leandro-lucarella-sociomantic** [comment]
Should be addressed by  #86. This one is too a bit in the edge for a patch-release, since this never worked, I prefer to consider it a "new feature" and require people to upgrade if they want to use it.
