### ISSUE TITLE
Provide a way to allow multiple directories for submodules

### ISSUE THREAD

**Issue by Geod24** [sociomantic-tsunami/makd#75]
Currently, when adding the ImportPath to the command line, Makd does the following:
```make
# Default dmd flags                                                                                                                                   
DIMPORTPATHS := -I$(GS) -I./$(SRC) $(foreach dep,$(SUBMODULES), -I./$(dep)/$(SRC))
override DFLAGS += $(DIMPORTPATHS)
```

This is problematic for 2 reasons:
- `SRC` is used as the project's source directory, and its submodules, which means submodules have to follow the same convention as the project, or the other way around.
- One might need to depend on multiple projects which follow different conventions.
  `dub` allows `src` and `source` (or to configure it from `dub.{json,sdl}`), which sounds like a sensible default.
  Example of problems: https://github.com/Calrama/llvm-d & https://github.com/Hackerpilot/libdparse (former uses `source`, later uses `src`).

**Comment by leandro-lucarella-sociomantic** [comment]
I'm not sure if it's worth adding such a complexity for exceptions. You can always add includes to `DFLAGS` if you have anything non-MakD-standard. I think this is a bit more verbose but safer and more reasonable than blindly passing a lot of `-I` options to the compiler in the hopes that someone will put interesting stuff there.

I'm very tempted to close this as `wontfix`... :)

**Comment by mathias-lang-sociomantic** [comment]
Alright, the workaround is reasonable and works for me :)
