### ISSUE TITLE
Release v2.0.0

### ISSUE THREAD

**Issue by mihails-strasuns-sociomantic** [sociomantic-tsunami/makd#87]
v2.x.x branch has accumulated quite some changes that can't be yet used in apps because there is no tagged release for it. Would be nice to get v2.0.0 at the same time as v1.10.0

**Comment by llucax** [comment]
> v2.x.x branch has accumulated quite some changes that can't be yet
> used in apps because there is no tagged release for it. Would be nice
> to get v2.0.0 at the same time as v1.10.0

Yeah, it is time. We should make sure to make any other cleanups /
breaking changes before the release.

**Comment by leandro-lucarella-sociomantic** [comment]
v1.10.0 was released, so we should be now able to release v2.0.0, but there were a couple of non-trivial conflict resolutions while rebasing on top of v1.10.0, so it would be nice if some brave are willing to update to the unreleased v2.0.0 (after going through v1.10.0 to have a smooth path probably) and do some real-world testing. I'm a bit concerned about releasing it without further testing in the current state.

**Comment by leandro-lucarella-sociomantic** [comment]
Maybe @joseph-wakeling-sociomantic or @mathias-baumann-sociomantic or @nemanja-boric-sociomantic are good candidates?

**Comment by leandro-lucarella-sociomantic** [comment]
Changes since v1.10.0: https://github.com/sociomantic-tsunami/makd/compare/v1.x.x...v2.0.0-rc1

**Comment by leandro-lucarella-sociomantic** [comment]
I created https://github.com/sociomantic-tsunami/makd/releases/tag/v2.0.0-rc1 to make testing more encouraging :D

**Comment by joseph-wakeling-sociomantic** [comment]
@leandro-lucarella-sociomantic happy to do some testing here, but would like to get all team apps upgraded to v1.10.0 first.

**Comment by mihails-strasuns-sociomantic** [comment]
I will need to make compatibility release in turtle for for v2 before it can be widely tested

**Comment by mihails-strasuns-sociomantic** [comment]
https://github.com/sociomantic-tsunami/turtle/issues/3

**Comment by joseph-wakeling-sociomantic** [comment]
@leandro-lucarella-sociomantic for projects without integration tests:

```
find: ‘/home/me/projectdir/integrationtest’: No such file or directory
find: ‘/home/me/projectdir/integrationtest’: No such file or directory
```

... is a bit intrusive in the build log.

I also get an error message when building the `pkg` target:

```
   mkpkg pkg/whatever.pkg
No name given for this package (set name with '-n', for example, '-n packagename') {:level=>:fatal}
```

... so do I presume right that the package name must now be explicitly set rather than inferred from the `.pkg` file name?  I don't think this is covered in the release notes.

**Comment by leandro-lucarella-sociomantic** [comment]
> @leandro-lucarella-sociomantic for projects without integration tests:

maybe you should write integration tests :trollface:

**Comment by leandro-lucarella-sociomantic** [comment]
> ... so do I presume right that the package name must now be explicitly set rather than inferred from the .pkg file name? I don't think this is covered in the release notes.

nope, this looks like a regression.

**Comment by joseph-wakeling-sociomantic** [comment]
> ... so do I presume right that the package name must now be explicitly set rather than inferred from the .pkg file name?

Ahh, I was missing the `import defaults` which takes care of this.  Ignore.

**Comment by leandro-lucarella-sociomantic** [comment]
Jokes aside, please report problems as separate issues.

**Comment by leandro-lucarella-sociomantic** [comment]
(both problems you mention deserve their own issues)

**Comment by joseph-wakeling-sociomantic** [comment]
I don't think the second one is an actual problem.  I've raised an issue for the first.

**Comment by leandro-lucarella-sociomantic** [comment]
It seems like we are ready to roll!
