### ISSUE TITLE
make d2conv doesn't take result into account

### ISSUE THREAD

**Issue by mathias-lang-sociomantic** [sociomantic-tsunami/makd#89]
```
% make d2conv
   d1to2fix build/devel/tmp/d2conv.stamp
d1to2fix.symbolsearch.SymbolSearchRecursionError@(./src/d1to2fix/symbolsearch.d:50): Soft recursion limit for symbol search has been reached.
Stack of last checked symbols:
BLAHBLAHBLAH

submodules/makd/Makd.mak:667: recipe for target 'XXX/build/devel/tmp/d2conv.stamp' failed
make: *** [XXX/build/devel/tmp/d2conv.stamp] Error 1
% make d2conv
make: Nothing to be done for 'd2conv'.
```

**Comment by llucax** [comment]
In theory the fix for this in MakD's side is very easy, but it is somehow tricky on `d1to2fix`. Are we sure `d1to2fix` is atomic in terms not really writing anything unless there will be no errors? If not, then if d1to2fix does a partial conversion, running it again will result in broken, doubly-converted, files.

/cc @mihails-strasuns-sociomantic

**Comment by llucax** [comment]
For the records, the fix in MakD would be to just write to another temporary file instead of `$@` in https://github.com/sociomantic-tsunami/makd/blob/v1.8.4/Makd.mak#L666. Then write `$@` after `d1to2fix` finished.

**Comment by mathias-lang-sociomantic** [comment]
> In theory the fix for this in MakD's side is very easy, but it is somehow tricky on d1to2fix. Are we sure d1to2fix is atomic in terms not really writing anything unless there will be no errors? If not, then if d1to2fix does a partial conversion, running it again will result in broken, doubly-converted, files.

I don't understand the rationale here. If there is an error the result is broken anyway, because `d1to2fix` can leave empty files.

**Comment by llucax** [comment]
So then you need manual intervention. This is why MakD alone can't do much to deal with this situation, whatever is done by MakD, will leave the project broken.

**Comment by Geod24** [comment]
I think we can just close this as WONTFIX
