### ISSUE TITLE
v2.0.0 release notes should mention that -unittest flag is no longer used when building integration tests

### ISSUE THREAD

**Issue by joseph-wakeling-sociomantic** [sociomantic-tsunami/makd#95]
The v2.0.0 release no longer uses the `-unittest` flag (at least by default) when building integration test suites.  Since at least one application has been found whose integration tests relied on functionality inside a `version (UnitTest)` block, this change should be clearly documented in the release notes, with suggestions for how to address the problem.

**Comment by leandro-lucarella-sociomantic** [comment]
Duplicate of #91. Sort of. Not really, but #91 will fix this one too. I will add there one more note about being careful with `version (UnitTest)` blocks.

PS: Wonderful, now GitHub doesn't mark duplicate issues as such anymore using the keyword...
